[package]
name = "gd-binding-gen"
version = "0.1.0"
edition = "2021"



[dependencies]
clap = {version = "^4.5.21",  features = ["derive"]}
clap_derive = "^4.5.18"
lazy-regex = "^3.3.0"
serde_json = "1.0.133"


